GeographicLib: CartConvert.cpp File Reference
CartConvert.cpp File Reference
Command line utility for geodetic to cartesian coordinate conversions.
#include "GeographicLib/Geocentric.hpp"
#include "GeographicLib/LocalCartesian.hpp"
#include "GeographicLib/DMS.hpp"
#include <iostream>
#include <iomanip>
#include <sstream>
Functions
int usage (int retval)
int main (int argc, char *argv[])
Detailed Description
Command line utility for geodetic to cartesian coordinate conversions.
Copyright (c) Charles Karney (2009, 2010) <charles@karney.com> and licensed under the LGPL. For more information, see http://geographiclib.sourceforge.net/
Compile with -I../include and link with Geocentric.o LocalCartesian.o
See CartConvert for usage information.
Definition in file CartConvert.cpp.
Function Documentation
int usage (int retval)
Definition at line 21 of file CartConvert.cpp.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 50 of file CartConvert.cpp.
References GeographicLib::DMS::Decode(), GeographicLib::DMS::DecodeLatLon(), GeographicLib::Geocentric::Forward(), GeographicLib::LocalCartesian::Forward(), GeographicLib::Geocentric::Reverse(), GeographicLib::LocalCartesian::Reverse(), usage(), GeographicLib::Constants::WGS84_a(), and GeographicLib::Constants::WGS84_r().